site_name: k8s for Admins
site_url: https://zahlenhelfer.github.io/k8s-for-admins/
nav:
  - Home: index.md
  - Node-Setup:
      - Getting Started: setup/cluster.md
      - Ingress: setup/ingress.md
  - Workloads:
  - Compliance:
      - Kyverno-Admission: compliance/kyverno/kyverno-labels.md
  - Storage:
      - Nfs: storage/nfs.md
      - HostPath: storage/hostpath.md
  - CI/CD:
      - Kustomize:
          - Basics: kustomize/kustomize.md
      - crds:
          - Custom Resource Definitions: crds/simple-crd.md
  - Observability:
      - Monitoring:
          - Metrics-Server & Grafana: oberservability/monitoring/prometheus.md
          - Metrics-Server & TLS: oberservability/monitoring/grafana.md
  - Security:
      - Host:
          - Scan your Hosts (Nmap): security/nmap.md
          - Firewall: security/firewall-ufw.md
          - Firewall with Ansible: security/firewall-ansible.md
      - Network:
      - Kubeconfig:
          - Kubeconfig: security/kubeconfig.md
      - general:
          - Suricata: security/suricata.md

theme: readthedocs
plugins:
  - search
  - print-site
