site_name: k8s for Admins
site_url: https://zahlenhelfer.github.io/k8s-for-admins/
nav:
        - Home: index.md
        - Node-Setup:
                  - Getting Started: setup/cluster.md
                  - Types:
                            - Ingress: setup/ingress.md
        - Kubernetes-Essentials:
                  - Storage:
                            - Nfs: storage/nfs.md
                            - HostPath: storage/hostpath.md
                  - Kustomize:
                            - Basics: kustomize/kustomize.md
                  - crds:
                            - Custom Resource Definitions: crds/simple-crd.md
                  - Monitoring:
                            - Metrics-Server & Grafana: monitoring/prometheus.md
                            - Metrics-Server & TLS: monitoring/grafana.md
                  - Security:
                            - Kyverno-Admission: security/rbac.md
                            - Kubeconfig: security/network-policies.md
                            - Advanced:
                                      - Suricata: security/suricata.md
                                      - Nmap-Scan: security/nmap.md

theme: readthedocs
plugins:
        - search
        - print-site
