site_name: k8s for Admins
site_url: https://zahlenhelfer.github.io/k8s-for-admins/
nav:
        - Home: index.md
        - Node-Setup:
                  - Getting Started: setup/cluster.md
                  - Types:
                            - Ingress: setup/ingress.md
        - Kubernetes-Essentials:
                  - Storage:
                            - Nfs: storage/nfs.md
                            - HostPath: storage/hostpath.md

theme: readthedocs
plugins:
        - search
        - print-site
