site_name: k8s for Admins
site_url: https://zahlenhelfer.github.io/k8s-for-admins/
#theme: readthedocs
theme:
  name: material # Material theme for MkDocs
  logo: img/k8s_logo.svg # Path to your logo file
  features:
    - content.code.copy # Enables code copy feature
    - content.code.select # Enables code select feature
    - navigation.tracking # Enables navigation tracking feature
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search: # Enables search functionality
      lang:
        - en
        - de
  - awesome-nav
  - mermaid2
  - git-revision-date-localized
  - exporter:
      formats:
        pdf:
          concurrency: 1
      buttons:
        - title: Download as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  - minify:
      minify_html: true
