# This is a basic workflow to help you get started with Actions

name: Generate and deploy mkdocs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - '.github/workflows/cicd.yaml'
  workflow_dispatch:

permissions:
  contents: write  # REQUIRED to push to gh-pages

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all Git history (branches, tags, etc.)

      - uses: actions/setup-python@v5
        with:
          #python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Cache Playwright browsers
        id: cache-playwright
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          if [ -z "${{ steps.cache-playwright.outputs.cache-hit }}" ]; then
            playwright install --with-deps
          fi

      - name: Publish docs
        run: mkdocs gh-deploy --force